#pragma once

#define EE_HANDS

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 1000U

#define SERIAL_USART_TX_PIN GP0
#define SERIAL_PIO_USE_PIO1 // Force the usage of PIO1 peripheral, by default the Serial implementation uses the PIO0 peripheral

#define ANALOG_JOYSTICK_X_AXIS_PIN GP26
#define ANALOG_JOYSTICK_Y_AXIS_PIN GP27

#define ANALOG_JOYSTICK_AXIS_MIN 272

#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_COMBINED
// #define POINTING_DEVICE_ROTATION_90_RIGHT

// #define POINTING_DEVICE_ROTATION_90
// POINTING_DEVICE_ROTATION_180
// POINTING_DEVICE_ROTATION_270
